name: Azure SQL Edge with SQLCMD in Docker

on: push

jobs:
  sql-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Azure SQL Edge Container
        run: |
          docker run -d --name azuresqledge \
            -e 'ACCEPT_EULA=Y' \
            -e 'SA_PASSWORD=YourStrongPassword1!' \
            -p 1433:1433 \
            mcr.microsoft.com/azure-sql-edge

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server to start..."
          for i in {1..30}; do
            docker run --rm --network=host mcr.microsoft.com/mssql-tools bash -c \
              "sqlcmd -S localhost -U sa -P 'YourStrongPassword1!' -Q 'SELECT @@VERSION'" && break
            echo "SQL Server not ready yet..."
            sleep 5
          done

      - name: Create Test Database
        run: |
          docker run --rm --network=host mcr.microsoft.com/mssql-tools bash -c \
            "sqlcmd -S localhost -U sa -P 'YourStrongPassword1!' -Q 'CREATE DATABASE TestDB'"

      - name: Verify Database Creation
        run: |
          docker run --rm --network=host mcr.microsoft.com/mssql-tools bash -c \
            "sqlcmd -S localhost -U sa -P 'YourStrongPassword1!' -Q 'SELECT name FROM sys.databases'"
