name: Build Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

#    container:
#      image: maven:3.9.6-eclipse-temurin-21

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Set up settings.xml
        run: |
          mkdir -p $GITHUB_WORKSPACE/.m2
          echo "<settings>
              <mirrors>
                 <mirror>
                  <id>bax-mirror</id>
                  <url>https://pkgs.dev.azure.com/techcloud0/_packaging/bax/maven/v1</url>
                  <mirrorOf>*</mirrorOf>
                </mirror>
             </mirrors>
                  <servers>
                    <server>
                      <id>bax-mirror</id>
                      <username>techcloud0</username>
                      <password>${{ secrets.AZURE_PAT_BAXDES_TEMP }}</password>
                    </server>
                  </servers>
                </settings>" > $GITHUB_WORKSPACE/.m2/settings.xml

      - name: Java verson
        run: java -version

      - name: Maven version
        run: mvn -v

      - name: view settings.xml
        run: head -5 $GITHUB_WORKSPACE/.m2/settings.xml

      - name: Build with Maven
        run: mvn -Drevision=${{ github.sha }} -B package --file pom.xml
#       run: mvn -s $GITHUB_WORKSPACE/.github/settings.xml -Drevision=${{ github.sha }} -B package --file pom.xml
#        env:
#          AZURE_PAT_BAXDES_TEMP: ${{ secrets.AZURE_PAT_BAXDES_TEMP }}


