name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Java version
        run: java -version

      - name: Maven version
        run: mvn -v

      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml


