name: Build Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    #    container:
    #      image: maven:3.9.6-eclipse-temurin-21

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup JDK 21 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven


      #      - name: Setup Maven settings.xml
      #        run: |
      #          mkdir -p $GITHUB_WORKSPACE/.m2
      #          echo "<settings>
      #                  <mirrors>
      #                    <mirror>
      #                      <id>bax-mirror</id>
      #                      <url>https://pkgs.dev.azure.com/techcloud0/_packaging/bax/maven/v1</url>
      #                      <mirrorOf>*</mirrorOf>
      #                    </mirror>
      #                  </mirrors>
      #                  <servers>
      #                    <server>
      #                      <id>bax-mirror</id>
      #                      <username>techcloud0</username>
      #                      <password>${{ secrets.AZURE_PAT_BAXDES_TEMP }}</password>
      #                    </server>
      #                  </servers>
      #                </settings>" > $GITHUB_WORKSPACE/.m2/settings.xml

      - name: Java version
        run: java -version

      - name: Maven version
        run: mvn -v

      - name: Build
        run: mvn -Drevision=${{ github.sha }} -B package

      - name: Publish package
        run: mvn -Drevision=${{ github.sha }} --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Publish package
#        run: mvn -Drevision=${{ github.sha }} --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#
