name: Build Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Java version
        run: java -version

      - name: Maven version
        run: mvn -v

      - name: Print secret
        run: echo ${{ secrets.MY_TEST_SECRET }}

      - name: Print sha
        run: echo ${{ vars.MY_VARIABLE }}

      - name: Print var
        run: echo ${{ github.sha }}

      - name: Check out repository
        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: temurin
#          cache: maven

#      - name: Java version
#        run: java -version
#
#      - name: Maven version
#        run: mvn -v

      - name: Build with Maven
        run: mvn -Drevision=${{ github.sha }} -B package --file pom.xml


