name: Download Artifact

on:
  push:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Download artifact
        run: |
          echo "Downloading artifact from the previous workflow..."
          mvn dependency:get \
          -s "$GITHUB_WORKSPACE/.github/settings.xml" \
          -Dartifact=org.eirik:spring-demo:0.0.1-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy artifact
        run: |
          mvn dependency:copy \
          -Dartifact=org.eirik:spring-demo:0.0.1-SNAPSHOT \
          -DoutputDirectory=$GITHUB_WORKSPACE
